### ISSUE TITLE
Accessing undefined method "date"

### ISSUE THREAD

**Issue by pserwylo** [sverrirs/jekyll-paginate-v2#29]
The fix for #12 in [paginationModel.rb#L230](https://github.com/sverrirs/jekyll-paginate-v2/blob/master/lib/jekyll-paginate-v2/generator/paginationModel.rb#L230) assumes that all Jekyll::Document objects have a `date` property. For the [F-Droid website](https://gitlab.com/fdroid/fdroid-website) we have a generator which outputs one page per Android application in our website. These don't have a date, and so it fails with the following error:

```
/home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-paginate-v2-1.8.0/lib/jekyll-paginate-v2/generator/paginationModel.rb:230:in `block in paginate': undefined method `date' for #<Jekyll:Page @name="subreddit.android.appstore/index.html"> (NoMethodError)
Did you mean?  data
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-paginate-v2-1.8.0/lib/jekyll-paginate-v2/generator/paginationModel.rb:229:in `each'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-paginate-v2-1.8.0/lib/jekyll-paginate-v2/generator/paginationModel.rb:229:in `paginate'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-paginate-v2-1.8.0/lib/jekyll-paginate-v2/generator/paginationModel.rb:67:in `block in run'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-paginate-v2-1.8.0/lib/jekyll-paginate-v2/generator/paginationModel.rb:34:in `each'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-paginate-v2-1.8.0/lib/jekyll-paginate-v2/generator/paginationModel.rb:34:in `run'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-paginate-v2-1.8.0/lib/jekyll-paginate-v2/generator/paginationGenerator.rb:129:in `generate'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:174:in `block in generate'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:172:in `each'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:172:in `generate'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:68:in `process'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/bundler/gems/polyglot-ea0b78b397e8/lib/jekyll/polyglot/patches/jekyll/site.rb:66:in `process_active_language'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/bundler/gems/polyglot-ea0b78b397e8/lib/jekyll/polyglot/patches/jekyll/site.rb:57:in `process_language'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/bundler/gems/polyglot-ea0b78b397e8/lib/jekyll/polyglot/patches/jekyll/site.rb:24:in `block (2 levels) in process'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/bundler/gems/polyglot-ea0b78b397e8/lib/jekyll/polyglot/patches/jekyll/site.rb:23:in `fork'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/bundler/gems/polyglot-ea0b78b397e8/lib/jekyll/polyglot/patches/jekyll/site.rb:23:in `block in process'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/bundler/gems/polyglot-ea0b78b397e8/lib/jekyll/polyglot/patches/jekyll/site.rb:22:in `each'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/bundler/gems/polyglot-ea0b78b397e8/lib/jekyll/polyglot/patches/jekyll/site.rb:22:in `process'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-3.4.3/lib/jekyll/command.rb:26:in `process_site'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-3.4.3/lib/jekyll/commands/build.rb:63:in `build'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-3.4.3/lib/jekyll/commands/build.rb:34:in `process'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-3.4.3/lib/jekyll/commands/serve.rb:37:in `block (2 levels) in init_with_program'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-3.4.3/exe/jekyll:13:in `<top (required)>'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/bin/jekyll:22:in `load'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/bin/jekyll:22:in `<main>'
```

I'm happy to submit a PR which wrapped the relevant block of code in something like `if p.responds_to? "date"`, but my Ruby knowledge is not strong enough to know if that is an idiomatic way to solve this problem.

**Comment by sverrirs** [comment]
Hi Peter, 

Sorry you're having problems with the plugin. I would be happy to accept a PR if you have the time.  :)

**Comment by pserwylo** [comment]
Not a problem. PR coming up.
